version: "2.1"
services:
  server:
    build:
      context: ./app
      dockerfile: Dockerfile.debug
    ports:
      - "8888:4000"
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "echo", "show dbs", "|", "mongo"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: mongod --smallfiles
